#include "keyboard.h"
#include "type.h"

/*矩阵键盘模块行和列引脚*/
sbit COL4 = P1^0; // 第1行
sbit COL3 = P1^1; // 第2行
sbit COL2 = P1^2; // 第3行
sbit COL1 = P1^3; // 第4行
sbit ROW4 = P1^4; // 第1行
sbit ROW3 = P1^5; // 第2列
sbit ROW2 = P1^6; // 第3列
sbit ROW1 = P1^7; // 第4列

/*矩阵键盘模块按键状态*/
bit KEYBOARD1_OLD = 1 , KEYBOARD2_OLD = 1, KEYBOARD3_OLD = 1, KEYBOARD4_OLD = 1,
		KEYBOARD5_OLD = 1, KEYBOARD6_OLD = 1, KEYBOARD7_OLD = 1, KEYBOARD8_OLD = 1, 
		KEYBOARD9_OLD = 1, KEYBOARD10_OLD = 1, KEYBOARD11_OLD = 1, KEYBOARD12_OLD = 1, 
		KEYBOARD13_OLD = 1, KEYBOARD14_OLD = 1, KEYBOARD15_OLD = 1, KEYBOARD16_OLD = 1;
bit KEYBOARD1_NEW = 1, KEYBOARD2_NEW = 1, KEYBOARD3_NEW = 1 , KEYBOARD4_NEW = 1,
		KEYBOARD5_NEW = 1, KEYBOARD6_NEW = 1, KEYBOARD7_NEW = 1 , KEYBOARD8_NEW = 1, 
		KEYBOARD9_NEW = 1, KEYBOARD10_NEW = 1, KEYBOARD11_NEW = 1, KEYBOARD12_NEW = 1, 
		KEYBOARD13_NEW = 1, KEYBOARD14_NEW = 1, KEYBOARD15_NEW = 1, KEYBOARD16_NEW = 1;
bit KEYBOARD1_DOWN = 0, KEYBOARD2_DOWN = 0, KEYBOARD3_DOWN = 0, KEYBOARD4_DOWN = 0,
		KEYBOARD5_DOWN = 0, KEYBOARD6_DOWN = 0, KEYBOARD7_DOWN = 0, KEYBOARD8_DOWN = 0, 
		KEYBOARD9_DOWN = 0, KEYBOARD10_DOWN = 0, KEYBOARD11_DOWN = 0, KEYBOARD12_DOWN = 0, 
		KEYBOARD13_DOWN = 0, KEYBOARD14_DOWN = 0, KEYBOARD15_DOWN = 0, KEYBOARD16_DOWN = 0;

/**
 * @brief 列方式进行矩阵键盘检测
 */
void detect_row_keyboard(){
	static char tmp_col = 0;
	switch(tmp_col){
		case 0:
			P1=0x7F;
			KEYBOARD1_NEW = COL1;
			KEYBOARD2_NEW = COL2;
			KEYBOARD3_NEW = COL3;
			KEYBOARD4_NEW = COL4;
			if(!KEYBOARD1_OLD && KEYBOARD1_NEW) KEYBOARD1_DOWN = 1;
			if(!KEYBOARD2_OLD && KEYBOARD2_NEW) KEYBOARD2_DOWN = 1;
			if(!KEYBOARD3_OLD && KEYBOARD3_NEW) KEYBOARD3_DOWN = 1;
			if(!KEYBOARD4_OLD && KEYBOARD4_NEW) KEYBOARD4_DOWN = 1;
			KEYBOARD1_OLD = KEYBOARD1_NEW;
			KEYBOARD2_OLD = KEYBOARD2_NEW;
			KEYBOARD3_OLD = KEYBOARD3_NEW;
			KEYBOARD4_OLD = KEYBOARD4_NEW;
			break;
		case 1:
			P1=0xBF;
			KEYBOARD5_NEW = COL1;
			KEYBOARD6_NEW = COL2;
			KEYBOARD7_NEW = COL3;
			KEYBOARD8_NEW = COL4;
			if(!KEYBOARD5_OLD && KEYBOARD5_NEW) KEYBOARD5_DOWN = 1;
			if(!KEYBOARD6_OLD && KEYBOARD6_NEW) KEYBOARD6_DOWN = 1;
			if(!KEYBOARD7_OLD && KEYBOARD7_NEW) KEYBOARD7_DOWN = 1;
			if(!KEYBOARD8_OLD && KEYBOARD8_NEW) KEYBOARD8_DOWN = 1;
			KEYBOARD5_OLD = KEYBOARD5_NEW;
			KEYBOARD6_OLD = KEYBOARD6_NEW;
			KEYBOARD7_OLD = KEYBOARD7_NEW;
			KEYBOARD8_OLD = KEYBOARD8_NEW;
			break;
		case 2:
			P1=0xDF;
			KEYBOARD9_NEW = COL1;
			KEYBOARD10_NEW = COL2;
			KEYBOARD11_NEW = COL3;
			KEYBOARD12_NEW = COL4;
			if(!KEYBOARD9_OLD && KEYBOARD9_NEW) KEYBOARD9_DOWN = 1;
			if(!KEYBOARD10_OLD && KEYBOARD10_NEW) KEYBOARD10_DOWN = 1;
			if(!KEYBOARD11_OLD && KEYBOARD11_NEW) KEYBOARD11_DOWN = 1;
			if(!KEYBOARD12_OLD && KEYBOARD12_NEW) KEYBOARD12_DOWN = 1;
			KEYBOARD9_OLD = KEYBOARD9_NEW;
			KEYBOARD10_OLD = KEYBOARD10_NEW;
			KEYBOARD11_OLD = KEYBOARD11_NEW;
			KEYBOARD12_OLD = KEYBOARD12_NEW;
			break;
		case 3:
			P1=0xEF;
			KEYBOARD13_NEW = COL1;
			KEYBOARD14_NEW = COL2;
			KEYBOARD15_NEW = COL3;
			KEYBOARD16_NEW = COL4;
			if(!KEYBOARD13_OLD && KEYBOARD13_NEW) KEYBOARD13_DOWN = 1;
			if(!KEYBOARD14_OLD && KEYBOARD14_NEW) KEYBOARD14_DOWN = 1;
			if(!KEYBOARD15_OLD && KEYBOARD15_NEW) KEYBOARD15_DOWN = 1;
			if(!KEYBOARD16_OLD && KEYBOARD16_NEW) KEYBOARD16_DOWN = 1;
			KEYBOARD13_OLD = KEYBOARD13_NEW;
			KEYBOARD14_OLD = KEYBOARD14_NEW;
			KEYBOARD15_OLD = KEYBOARD15_NEW;
			KEYBOARD16_OLD = KEYBOARD16_NEW;
			break;
	}
	tmp_col++;
	tmp_col %= 4;
}

/**
 * @brief 行方式进行矩阵键盘检测
 */
void detect_col_keyboard(){
	static char tmp_col = 0;
	switch(tmp_col){
		case 0:
			P1=0xF7;
			KEYBOARD1_NEW = ROW1;
			KEYBOARD5_NEW = ROW2;
			KEYBOARD9_NEW = ROW3;
			KEYBOARD13_NEW = ROW4;
			if(!KEYBOARD1_OLD && KEYBOARD1_NEW) KEYBOARD1_DOWN = 1;
			if(!KEYBOARD5_OLD && KEYBOARD5_NEW) KEYBOARD5_DOWN = 1;
			if(!KEYBOARD9_OLD && KEYBOARD9_NEW) KEYBOARD9_DOWN = 1;
			if(!KEYBOARD13_OLD && KEYBOARD13_NEW) KEYBOARD13_DOWN = 1;
			KEYBOARD1_OLD = KEYBOARD1_NEW;
			KEYBOARD5_OLD = KEYBOARD5_NEW;
			KEYBOARD9_OLD = KEYBOARD9_NEW;
			KEYBOARD13_OLD = KEYBOARD13_NEW;
			break;
		case 1:
			P1=0xFB;
			KEYBOARD2_NEW = ROW1;
			KEYBOARD6_NEW = ROW2;
			KEYBOARD10_NEW = ROW3;
			KEYBOARD14_NEW = ROW4;
			if(!KEYBOARD2_OLD && KEYBOARD2_NEW) KEYBOARD2_DOWN = 1;
			if(!KEYBOARD6_OLD && KEYBOARD6_NEW) KEYBOARD6_DOWN = 1;
			if(!KEYBOARD10_OLD && KEYBOARD10_NEW) KEYBOARD10_DOWN = 1;
			if(!KEYBOARD14_OLD && KEYBOARD14_NEW) KEYBOARD14_DOWN = 1;
			KEYBOARD2_OLD = KEYBOARD2_NEW;
			KEYBOARD6_OLD = KEYBOARD6_NEW;
			KEYBOARD10_OLD = KEYBOARD10_NEW;
			KEYBOARD14_OLD = KEYBOARD14_NEW;
			break;
		case 2:
			P1=0xFD;
			KEYBOARD3_NEW = ROW1;
			KEYBOARD7_NEW = ROW2;
			KEYBOARD11_NEW = ROW3;
			KEYBOARD15_NEW = ROW4;
			if(!KEYBOARD3_OLD && KEYBOARD3_NEW) KEYBOARD3_DOWN = 1;
			if(!KEYBOARD7_OLD && KEYBOARD7_NEW) KEYBOARD7_DOWN = 1;
			if(!KEYBOARD11_OLD && KEYBOARD11_NEW) KEYBOARD11_DOWN = 1;
			if(!KEYBOARD15_OLD && KEYBOARD15_NEW) KEYBOARD15_DOWN = 1;
			KEYBOARD3_OLD = KEYBOARD3_NEW;
			KEYBOARD7_OLD = KEYBOARD7_NEW;
			KEYBOARD11_OLD = KEYBOARD11_NEW;
			KEYBOARD15_OLD = KEYBOARD15_NEW;
			break;
		case 3:
			P1=0xFE;
			KEYBOARD4_NEW = ROW1;
			KEYBOARD8_NEW = ROW2;
			KEYBOARD12_NEW = ROW3;
			KEYBOARD16_NEW = ROW4;
			if(!KEYBOARD4_OLD && KEYBOARD4_NEW) KEYBOARD4_DOWN = 1;
			if(!KEYBOARD8_OLD && KEYBOARD8_NEW) KEYBOARD8_DOWN = 1;
			if(!KEYBOARD12_OLD && KEYBOARD12_NEW) KEYBOARD12_DOWN = 1;
			if(!KEYBOARD16_OLD && KEYBOARD16_NEW) KEYBOARD16_DOWN = 1;
			KEYBOARD4_OLD = KEYBOARD4_NEW;
			KEYBOARD8_OLD = KEYBOARD8_NEW;
			KEYBOARD12_OLD = KEYBOARD12_NEW;
			KEYBOARD16_OLD = KEYBOARD16_NEW;
			break;
	}
	tmp_col++;
	tmp_col %= 4;
}